# Move issues and pull requests to the project

name: Add new issue or pull request to project

on:
  pull_request:
    types:
      - opened
  issues:
    types:
      - opened

jobs:
  add-to-project:
    name: Add issue to project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/add-to-project@v1
        with:
          # https://github.com/settings/tokens
          # https://github.com/mark-wiemer-org/ahkpp/settings/secrets/actions
          # Saved locally as "Add to project PAT"
          project-url: https://github.com/orgs/mark-wiemer-org/projects/1
          github-token: ${{ secrets.ADD_TO_PROJECT_PAT }}
